Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -27,33 +27,33 @@ stages:
                 echo "Activating virtual environment..."
                 source dev/Scripts/activate
                 curl https://pypi.org/simple
-                if [ $? -eq 0 ]; then
-                    echo "Project setup completed successfully."
-                else
-                    echo "Project setup failed."
-                    exit 1
-                fi
+                # if [ $? -eq 0 ]; then
+                #     echo "Project setup completed successfully."
+                # else
+                #     echo "Project setup failed."
+                #     exit 1
+                # fi
           
-          - task: AzureCLI@2
-            inputs:
-              azureSubscription: 'justpracticerepo'
-              scriptType: 'bash'
-              scriptLocation: 'inlineScript'
-              inlineScript: |
-                python3 -m venv dev
-                ls
-                echo "Activating virtual environment..."
-                source dev/Scripts/activate
-                curl https://pypi.org/simple
-                pip install --prefer-binary -r requirements.txt
-                if [ $? -eq 0 ]; then
-                    echo "Project setup completed successfully."
-                else
-                    echo "Project setup failed."
-                    exit 1
-                fi
-                export HTTPS_PROXY=http://proxy.its.hpecorp.net:8080
-                env | grep -i proxy
+          # - task: AzureCLI@2
+          #   inputs:
+          #     azureSubscription: 'justpracticerepo'
+          #     scriptType: 'bash'
+          #     scriptLocation: 'inlineScript'
+          #     inlineScript: |
+          #       python3 -m venv dev
+          #       ls
+          #       echo "Activating virtual environment..."
+          #       source dev/Scripts/activate
+          #       curl https://pypi.org/simple
+          #       pip install --prefer-binary -r requirements.txt
+          #       if [ $? -eq 0 ]; then
+          #           echo "Project setup completed successfully."
+          #       else
+          #           echo "Project setup failed."
+          #           exit 1
+          #       fi
+          #       export HTTPS_PROXY=http://proxy.its.hpecorp.net:8080
+          #       env | grep -i proxy
           
           - task: UsePythonVersion@0
             inputs:
