Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -22,6 +22,17 @@ stages:
                 mkdir -p /d/Projects/demo 
                 cp -r temp_project/* /d/Projects/demo
                 ls /d/Projects/demo/
+                python3 -m venv dev
+                ls
+                echo "Activating virtual environment..."
+                source dev/Scripts/activate
+                curl https://pypi.org/simple
+                if [ $? -eq 0 ]; then
+                    echo "Project setup completed successfully."
+                else
+                    echo "Project setup failed."
+                    exit 1
+                fi
           
           - task: AzureCLI@2
             inputs:
@@ -34,15 +45,15 @@ stages:
                 echo "Activating virtual environment..."
                 source dev/Scripts/activate
                 curl https://pypi.org/simple
-                # pip install --prefer-binary -r requirements.txt
-                # if [ $? -eq 0 ]; then
-                #     echo "Project setup completed successfully."
-                # else
-                #     echo "Project setup failed."
-                #     exit 1
-                # fi
-                # export HTTPS_PROXY=http://proxy.its.hpecorp.net:8080
-                # env | grep -i proxy
+                pip install --prefer-binary -r requirements.txt
+                if [ $? -eq 0 ]; then
+                    echo "Project setup completed successfully."
+                else
+                    echo "Project setup failed."
+                    exit 1
+                fi
+                export HTTPS_PROXY=http://proxy.its.hpecorp.net:8080
+                env | grep -i proxy
           
           - task: UsePythonVersion@0
             inputs:
@@ -52,3 +63,7 @@ stages:
           - script: |
               python -m pip install --upgrade pip setuptools wheel
               pip install --prefer-binary -r requirements.txt
+          - script: |
+              echo Python dependencies installed successfully! 
+              displayName: 'Success Message'
+              condition: succeeded()
