Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -21,4 +21,19 @@ stages:
                 git clone -b dev https://github.com/Thiru799/taxi-booking.git temp_project
                 ls
                 mkdir -p /d/Projects/demo 
-                cp /temp_project/* /d/Projects/demo
+                cp temp_project/* /d/Projects/demo
+          
+          - task: PythonScript@0
+            inputs:
+              scriptSource: 'inline'
+              script: |
+                python3 -m venv dev
+                source dev/bin/activate
+                export HTTPS_PROXY=http://proxy.its.hpecorp.net:8080
+                pip install -r requirements.txt
+                if [ $? -eq 0 ]; then
+                    echo "Project setup completed successfully."
+                else
+                    echo "Project setup failed."
+                    exit 1
+                fi
